# Generated by Django 4.1.4 on 2022-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=0, max_length=64, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
