# Generated by Django 4.1.4 on 2022-12-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='盲盒用户名')),
                ('hobby', models.CharField(blank=True, max_length=1000, null=True, verbose_name='个人简介')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('call', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='关联用户id')),
            ],
        ),
    ]
