# Generated by Django 4.1.4 on 2022-12-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_infomation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infomation',
            new_name='Information',
        ),
    ]
