# Generated by Django 4.1.4 on 2022-12-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_school_information_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='call',
            field=models.CharField(default=0, max_length=100, verbose_name='联系方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=0, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='hobby',
            field=models.CharField(default=0, max_length=1000, verbose_name='个人简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(default=0, max_length=64, verbose_name='盲盒用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.school', to_field='school', verbose_name='学校'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
