# Generated by Django 4.1.4 on 2022-12-26 06:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='富文本编辑器'),
            preserve_default=False,
        ),
    ]
