# Generated by Django 4.1.4 on 2022-12-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_comment_body_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题'),
        ),
    ]
