# Generated by Django 4.1.4 on 2022-12-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
