# Generated by Django 4.1.4 on 2022-12-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='app01.information', verbose_name='被评论对象'),
            preserve_default=False,
        ),
    ]
