# Generated by Django 4.1.4 on 2022-12-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_collection_information_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='collect',
        ),
        migrations.AddField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.information', unique=True),
        ),
    ]
