# Generated by Django 4.1.4 on 2022-12-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_commentreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='user',
            new_name='reply_user',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='replyed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.information', verbose_name='评论回复'),
        ),
    ]
