# Generated by Django 4.1.4 on 2022-12-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.information'),
        ),
    ]
