# Generated by Django 4.1.4 on 2022-12-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_alter_collection_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', to_field='name', verbose_name='评论的人'),
        ),
    ]
