# Generated by Django 4.1.4 on 2023-01-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_commentreply_user_alter_commentreply_reply_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=520, verbose_name='个性签名')),
                ('skills', models.CharField(max_length=520, verbose_name='技能')),
                ('QQ', models.IntegerField(verbose_name='QQ号')),
                ('Weixin', models.CharField(max_length=30, verbose_name='微信号')),
                ('Blogger_URL', models.CharField(max_length=100, verbose_name='url')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='关联的用户')),
            ],
        ),
    ]
