# Generated by Django 4.1.4 on 2023-01-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_alter_maininformation_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformation',
            name='skills',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='技能'),
        ),
    ]
