# Generated by Django 4.1.4 on 2023-01-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_alter_maininformation_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
