# Generated by Django 4.1.4 on 2023-01-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_alter_maininformation_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.information'),
        ),
    ]
